// Generated by CoffeeScript 1.8.0
(function() {
  module.exports = function(phrase, options) {
    var length;
    length = options.length;
    if (phrase.length <= length) {
      return phrase;
    }
    return phrase.substr(0, length - 1) + '…';
  };

}).call(this);
