// Generated by CoffeeScript 1.8.0
(function() {
  var truncateAtLength;

  module.exports = function(phrase, options) {
    var length, splitWords;
    length = options.length;
    splitWords = options.splitWords || false;
    if (phrase.length <= length) {
      return phrase;
    }
    if (splitWords) {
      return phrase.substr(0, length - 1) + '…';
    } else {
      return phrase.substr(0, length - 1) + '…';
    }
  };

  truncateAtLength = function(phrase, length) {
    return phrase.substr(0, length - 1) + '…';
  };

}).call(this);
