// Generated by CoffeeScript 1.8.0
(function() {
  var filter, last, truncateAtLength, truncateAtWordBoundary, _ref;

  _ref = require('underscore'), filter = _ref.filter, last = _ref.last;

  module.exports = function(phrase, options) {
    var length, splitWords;
    length = options.length;
    splitWords = options.splitWords || false;
    if (phrase.length <= length) {
      return phrase;
    }
    if (splitWords) {
      return truncateAtLength(phrase, length);
    } else {
      return truncateAtWordBoundary(phrase, length);
    }
  };

  truncateAtWordBoundary = function(phrase, length) {
    var lastPossibleWord, match, wordBoundaries, wordBoundaryRegex;
    wordBoundaryRegex = /\s/g;
    wordBoundaries = [];
    while (match = wordBoundaryRegex.exec(phrase)) {
      wordBoundaries.push(match.index);
    }
    lastPossibleWord = last(filter(wordBoundaries, function(boundary) {
      return boundary < length - 1;
    }));
    if (lastPossibleWord == null) {
      return truncateAtLength(phrase, length);
    }
    return truncateAtLength(phrase, lastPossibleWord + 1);
  };

  truncateAtLength = function(phrase, length) {
    var truncatedPhrase;
    truncatedPhrase = phrase.substr(0, length - 1);
    return truncatedPhrase.trimRight() + '…';
  };

}).call(this);
